name: armTemplateDeployment
on:
    push:
      branches:
          -main
    workflow_dispatch:
jobs:
  armDeploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Azure/Login
        uses: Azure/login@v2
        with:
          creds : ${{ secrets.AZURE_CREDENTIALS }}

      - name: Azure/Login
        uses: azure/cli@v2
        with:
          azcliversion: 2.30.0
          inlineScript: |
            az deployment sub create --location "UK West" --template-file ./arm-templates/resourcegroup.json  

    