name: armTemplateDeployment
on:
    push:
      branches:
          - main
    workflow_dispatch:
jobs:
  armDeploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Azure/Login
        uses: Azure/login@v2
        with:
          creds : ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy Resource Group rsg-githubactions with ARM Templates
        uses: Azure/arm-deploy@v2
        with:
          scope: subscription
          subscriptionId: a56b08c0-a01b-48ad-a668-d832c57951c8
          region: UK West
          template: ./arm-templates/resourcegroup.json
          parameters: 
            location="UK West"
            resourceGroupName=brmglobostg002
          deploymentName:  rsg-githubactions

      - name: Deploy Storage Account
        uses: Azure/arm-deploy@v2
        id: storageAccountDeploy
        with:
          scope: resourcegroup
          resourceGroupName: rsg-githubactions
          subscriptionId: a56b08c0-a01b-48ad-a668-d832c57951c8
          template: ./arm-templates/storageaccount.json
          parameters: 
            sku=Standard_LRS
            location="UK West"
            storageAccountName=brmglobostg002
          deploymentMode: incremental    

      - name: Deploy Virtual Machine
        uses: Azure/arm-deploy@v2          
        with:
          scope: resourcegroup
          resourceGroupName: rsg-githubactions
          subscriptionId: a56b08c0-a01b-48ad-a668-d832c57951c8
          template: ./arm-templates/virtualmachine.json
          parameters: 
            adminPassword="My$ecureP@ssword!"
          deploymentMode: incremental              


      # - run: echo ${{ steps.storageAccountDeploy.outputs.BlobUri  }}
      # - name: Deploy Resource Group rsg-githubactions with AZ CLI
      #   uses: azure/cli@v2
      #   with:
      #     azcliversion: 2.30.0
      #     inlineScript: |
      #       az deployment sub create --location "UK West" --template-file ./arm-templates/resourcegroup.json  

    